# Phase 14 additive repository ports.
# Merge these classes into backend/app/repositories/interfaces.py.

from app.repositories.models import AssignmentRecord, NotificationRecord, AuditEventRecord

class AssignmentRepository(ABC):
    @abstractmethod
    def create(self, record: AssignmentRecord) -> AssignmentRecord: ...
    @abstractmethod
    def get(self, assignment_id: str) -> AssignmentRecord | None: ...
    @abstractmethod
    def save(self, record: AssignmentRecord) -> AssignmentRecord: ...
    @abstractmethod
    def list_for_application(self, application_id: str) -> list[AssignmentRecord]: ...
    @abstractmethod
    def list_for_officer(self, officer_id: str) -> list[AssignmentRecord]: ...

class NotificationRepository(ABC):
    @abstractmethod
    def create(self, record: NotificationRecord) -> NotificationRecord: ...
    @abstractmethod
    def list_for_recipient(self, recipient_id: str) -> list[NotificationRecord]: ...
    @abstractmethod
    def save(self, record: NotificationRecord) -> NotificationRecord: ...

class AuditEventRepository(ABC):
    @abstractmethod
    def append(self, record: AuditEventRecord) -> AuditEventRecord: ...
    @abstractmethod
    def list(self, limit: int = 100) -> list[AuditEventRecord]: ...
