# Phase 17 additive repository ports. Merge into repositories/interfaces.py.

from app.repositories.models import OfficerProfileRecord, ConnectorJobRecord, DeadLetterRecord, MetricEventRecord

class OfficerRepository(ABC):
    @abstractmethod
    def create(self, record: OfficerProfileRecord) -> OfficerProfileRecord: ...
    @abstractmethod
    def get(self, officer_id: str) -> OfficerProfileRecord | None: ...
    @abstractmethod
    def list_for_department(self, department: str) -> list[OfficerProfileRecord]: ...
    @abstractmethod
    def save(self, record: OfficerProfileRecord) -> OfficerProfileRecord: ...

class ConnectorJobRepository(ABC):
    @abstractmethod
    def create(self, record: ConnectorJobRecord) -> ConnectorJobRecord: ...
    @abstractmethod
    def get(self, job_id: str) -> ConnectorJobRecord | None: ...
    @abstractmethod
    def save(self, record: ConnectorJobRecord) -> ConnectorJobRecord: ...
    @abstractmethod
    def due_jobs(self, now: datetime) -> list[ConnectorJobRecord]: ...

class DeadLetterRepository(ABC):
    @abstractmethod
    def create(self, record: DeadLetterRecord) -> DeadLetterRecord: ...
    @abstractmethod
    def list(self, limit: int = 100) -> list[DeadLetterRecord]: ...

class MetricEventRepository(ABC):
    @abstractmethod
    def create(self, record: MetricEventRecord) -> MetricEventRecord: ...
    @abstractmethod
    def list(self, limit: int = 500) -> list[MetricEventRecord]: ...
